version: "3.7"

services:
  app:
    image: pidisplay/pidisplay:master
    stop_grace_period: 10s
    volumes:
      - ${APP_DATA_DIR}:/app/data
      - ${LND_DATA_DIR}:/app/lnd:ro
    environment:
      - BITCOIN_IP=${BITCOIN_IP}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASS=${BITCOIN_RPC_PASS}
      - BITCOIN_RPC_PORT=${BITCOIN_RPC_PORT}
      - LND_IP=${LND_IP}
      - LND_GRPC_PORT=${LND_GRPC_PORT}
      - BTC_NETWORK=${BITCOIN_NETWORK}
  screen:
    image: pidisplay/renderer:main
    volumes:
        - ${APP_DATA_DIR}:/app/data
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev0.1:/dev/spidev0.1"
    depends_on:
      - app
